config/routes.rb
Rails.application.routes.draw do

  resources :snippets

  root 'pages#home'
  
  get 'about' => 'pages#about'

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:show, :edit, :update, :destroy]

  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Snippet.all
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render :show, status: :created, location: @snippet }
      else
        format.html { render :new }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { render :show, status: :ok, location: @snippet }
      else
        format.html { render :edit }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url, notice: 'Snippet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_params
      params.require(:snippet).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">boxply</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <!-- Navigation hiden
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Einleitung</a></li>
        <li><a href="#">Hauptteil</a></li>
        <li><a href="#">Schlussteil</a></li>
      </ul>
      -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>boxply</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67742492-1', 'auto');
  ga('send', 'pageview');

</script>

  <script id="bsJs">
    $(document).ready(function() {
      {/* activate sidebar */
      $('#sidebar').affix({
        offset: {
          top: 635
        }
      });

      /* activate scrollspy menu */
      var $body   = $(document.body);
      var navHeight = $('.navbar').outerHeight(true) + 10;

      $body.scrollspy({
        target: '#leftCol',
        offset: navHeight
      });

      /* smooth scrolling sections */
      $('a[href*=#]:not([href=#])').click(function() {
          if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
            if (target.length) {
              $('html,body').animate({
                scrollTop: target.offset().top - 50
              }, 1000);
              return false;
            }
          }
      });}
    });
  </script>


</head>
<body>

  <%= render "layouts/header" %>

    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
TEST!!!111!

app/views/pages/intro/introtext/_introtext_1.html.erb
<p id='fe_text1' class="panel-body">
  Sehr geehrte Frau Müller, <br><br> mit Begeisterung habe ich auf Ihrer Firmenwebsite gelesen, dass Sie auch ein Trainee-Programm anbieten. Da ich meine berufliche Zukunft in der Biotecnologie-Branche sehe und Musterfirma gleichermaßen Wert auf gute Beratung und auf guten Vertrieb legt, möchte ich gerne künftig Ihre Sales-Abteilung verstärken.
</p>

app/views/pages/intro/introtext/_introtext_2.html.erb
<p id='fe_text2' class="panel-body">
Sehr geehrter Herr Fischer, <br><br> als angehender Ingenieurinformatiker habe ich schon während meines Studiums Erfahrungen bei der Integration von Softwaremodulen in ein ablauffähiges Produkt gesammelt. Ich absolvierte mehrere Praktika in IT-Abteilungen, unter anderem bei der BMW Group.
</p>

app/views/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<h1>Editing Snippet</h1>

<%= render 'form' %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Snippets</h1>
<% @snippets.each do |snippet| %>
<div class="panel panel-default">
  <button class='btn btn-default' data-clipboard-target='intro_text1' data-clipboard-text='Default clipboard text from attribute' id='d_clip_button_intro1' title='Click me to copy to clipboard.'>
  <b>Kopieren</b>
</button>
  <p id='intro_text1' class="panel-body">
    <%= snippet.content %>
</p>
</div>
   <script>
  $(document).ready(function() {
    var clip = new ZeroClipboard($("#d_clip_button_intro1"))
   });
</script>
  <% end %>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @snippets.each do |snippet| %>
      <tr>
        <td><%= snippet.content %></td>
        <td><%= link_to 'Show', snippet %></td>
        <td><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
        <td><%= link_to 'Destroy', snippet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snippet', new_snippet_path %>

app/views/snippets/new.html.erb
<h1>New Snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @snippet.content %>
</p>

<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>